# Generated by Django 4.1.4 on 2022-12-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='apps/static/images/placeholder.png', upload_to='products/'),
        ),
    ]
